---

- hosts: win
  tasks:
  - name: Copy a folder recursively where the source is on the remote host
    ansible.windows.win_copy:
      src: \\server-ip\Temp
      dest: C:\vault
      remote_src: yes

- name: create a random password

  ansible.builtin.set_fact:

    my_pass: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"

- name: save pass
  local_action: copy content={{my_pass}} dest=c:\pass.txt
  
- name: debug
  debug:

    msg: "{{ my_pass }}"

  - name: Create a new service with extra details
    ansible.windows.win_service:
      name: Vault Agent
      path: C:\vault\vault.exe
      display_name: Vault Agent
      description: Vault agent service

  - name: Stop service vault
    win_service:
      name:  Vault Agent
      state: start
